
DROP DATABASE IF EXISTS PROPERTY_MANAGEMENT;
CREATE DATABASE PROPERTY_MANAGEMENT; 
USE PROPERTY_MANAGEMENT;

DROP TABLE IF EXISTS CONTRACT;
DROP TABLE IF EXISTS PROPERTY;
DROP TABLE IF EXISTS LANDLORD;
DROP TABLE IF EXISTS RENTER;
DROP TABLE IF EXISTS MANAGER;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
	userID INTEGER NOT NULL,
	fName VARCHAR(30) NOT NULL,
	lName VARCHAR(30) NOT NULL,
	email VARCHAR(30) NOT NULL,
	pass VARCHAR(30) NOT NULL,
	dob DATE NOT NULL,
	PRIMARY KEY(userID)
);

CREATE  TABLE LANDLORD (
	landlordID INTEGER NOT NULL,
	PRIMARY KEY (landlordID),
	FOREIGN KEY (landlordID) REFERENCES USER(userID)
);

CREATE  TABLE RENTER (
	renterID INTEGER NOT NULL,
	PRIMARY KEY (renterID),
	FOREIGN KEY (renterID) REFERENCES USER(userID)
);

CREATE  TABLE MANAGER (
	managerID INTEGER NOT NULL,
	PRIMARY KEY (managerID),
	FOREIGN KEY (managerID) REFERENCES USER(userID)
);

CREATE TABLE PROPERTY (
	propertyID INTEGER NOT NULL, 
    landlordID INTEGER NOT NULL, 
    price DECIMAL(15, 2) NOT NULL,
    address VARCHAR(30) NOT NULL,
	propertyType VARCHAR(30) NOT NULL,
    quadrant VARCHAR(2) NOT NULL, 
	state VARCHAR(30) NOT NULL,
	noBedrooms INTEGER NOT NULL,
    noBathrooms INTEGER NOT NULL,
    isFurnished TINYINT(1),
	PRIMARY KEY (propertyID),
	FOREIGN KEY(landlordID) REFERENCES LANDLORD(landlordID)
);

CREATE TABLE CONTRACT (
	contractID INTEGER NOT NULL,
	landlordID INTEGER NOT NULL,
	renterID INTEGER NOT NULL,
	startDate DATE NOT NULL,
	endDate DATE NOT NULL,
	monthlyRent DECIMAL(15, 2) NOT NULL,
	PRIMARY KEY (contractID),
	FOREIGN KEY (landlordID) REFERENCES LANDLORD(landlordID),
	FOREIGN KEY (renterID) REFERENCES RENTER(renterID)
);